### ISSUE TITLE
getPermissionTo not working until run php artisan cache:forget spatie.permission.cache

### ISSUE THREAD

**Issue by loveyuxiao** [vyuldashev/nova-permission#43] opened 2018-10-07 11:50 UTC
attach permission to role, and the User has the role.
i can see the user has all permission:
            Text::make('name', function () use ($request) {
                return $request->user()->getAllPermissions()->pluck('name');
            }),
but i use $request->user()->hasPermissionTo('User_Edit'), it return false。
after i run php artisan cache:forget spatie.permission.cache 。it return true and work fun....

**Comment by XGhozt** [comment] 2018-10-17 04:17
+1 only way I was able to get new permissions that were attached to a role to show up on the user was to clear the cache and/or logout and login again.

**Comment by XGhozt** [comment] 2018-10-17 04:18
Actually this is a duplicate of #4

**Closed** 2018-12-18 16:03 UTC

**Comment by vyuldashev** [comment] 2018-12-18 16:04
Just tagged v1.4.4, the bug should disappear now.
